package projeto.classes;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class MenuOperacoes extends javax.swing.JFrame {
    
    private final Atletica atleticaRegistrada; // Referência a instância de Atletica para o qual a GUI de MenuOperacoes se refere
    private final Pessoa usuarioLogado; // Referência a instância de Pessoa do usuário do sistema logado no momento
    private String pathEncomendasProduto;
    
    /**
     * Creates new form MenuOperacoes
     * @param usuario
     * @param atleticaECA
     */
    public MenuOperacoes(Pessoa usuario, Atletica atleticaECA) {
        initComponents();
        labelUsuarioLogado.setText("Usuário logado: " + usuario.getRa());
        labelCargoAreaUsuarioLogado.setText("Cargo do usuário: " + usuario.getClass().getSimpleName());
        atleticaRegistrada = atleticaECA;
        usuarioLogado = usuario;
        pathEncomendasProduto = "";
    }
    
    // Getter usuarioLogado
    public Pessoa getUsuarioLogado(){
        return usuarioLogado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoVendaCompra = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        botaoTelaGerarMovimentacao = new javax.swing.JButton();
        botaoTelaGerarRelatorio = new javax.swing.JButton();
        botaoTelaVisualizarEstoque = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelUsuarioLogado = new javax.swing.JLabel();
        botaoSairUsuario = new javax.swing.JButton();
        labelCargoAreaUsuarioLogado = new javax.swing.JLabel();
        botaoCadastrarProduto = new javax.swing.JButton();
        telasOperacoes = new javax.swing.JTabbedPane();
        movimentacao = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        areasMovimentacao = new javax.swing.JComboBox<>();
        valorMovimentacao = new javax.swing.JTextField();
        descricaoMovimentacao = new javax.swing.JTextField();
        radioCompra = new javax.swing.JRadioButton();
        radioVenda = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        botaoGerarMovimentacao = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        movimentacaoMensagem = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        produtosEstoque = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        labelPrecoCompraProduto = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        labelPrecoVendaProduto = new javax.swing.JLabel();
        botaoRegistrarVenda = new javax.swing.JButton();
        statusVenda = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        labelQuantidadeDisponivelProduto = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        quantidadeProdutoVenda = new javax.swing.JTextField();
        gerarRelatorio = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        areasExtrato = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelSaldoInicio = new javax.swing.JLabel();
        labelSaldoAtual = new javax.swing.JLabel();
        labelBalanco = new javax.swing.JLabel();
        labelTotalMembros = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelMembrosArea = new javax.swing.JLabel();
        labelSaldoArea = new javax.swing.JLabel();
        botaoGerarRelatorio = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        telefoneClienteRetirada = new javax.swing.JTextField();
        botaoRegistrarRetirada = new javax.swing.JButton();
        statusRetirada = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nomeProdutoRetirada = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        scrollVisualizarEstoque = new javax.swing.JScrollPane();
        tabelaEstoque = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        anoProducaoProduto = new javax.swing.JTextField();
        precoVendaProduto = new javax.swing.JTextField();
        precoCompraProduto = new javax.swing.JTextField();
        nomeProduto = new javax.swing.JTextField();
        botaoCadastrarNovoProduto = new javax.swing.JButton();
        escolheArquivoEncomenda = new javax.swing.JFileChooser();
        jLabel30 = new javax.swing.JLabel();
        statusCadastrarProduto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Operações - Sistema de Gerenciamento AAAECA");
        setName("telaMenu"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        botaoTelaGerarMovimentacao.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        botaoTelaGerarMovimentacao.setText("Gerar Movimentação");
        botaoTelaGerarMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTelaGerarMovimentacaoActionPerformed(evt);
            }
        });

        botaoTelaGerarRelatorio.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        botaoTelaGerarRelatorio.setText("Gerar Relatório");
        botaoTelaGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTelaGerarRelatorioActionPerformed(evt);
            }
        });

        botaoTelaVisualizarEstoque.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        botaoTelaVisualizarEstoque.setText("Visualizar Estoque");
        botaoTelaVisualizarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTelaVisualizarEstoqueActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 3, 20)); // NOI18N
        jLabel1.setText("Operações");

        // Se receber um erro ao tentar abrir o arquivo, sugere-se trocar para o relative path de logoinblack.png em sua máquina
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("./logoinblack.png"))); // NOI18N

        labelUsuarioLogado.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        labelUsuarioLogado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botaoSairUsuario.setFont(new java.awt.Font("FreeSans", 1, 16)); // NOI18N
        botaoSairUsuario.setForeground(new java.awt.Color(255, 0, 0));
        botaoSairUsuario.setText("SAIR");
        botaoSairUsuario.setName("botaoSairUsuario"); // NOI18N
        botaoSairUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairUsuarioActionPerformed(evt);
            }
        });

        labelCargoAreaUsuarioLogado.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        labelCargoAreaUsuarioLogado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botaoCadastrarProduto.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        botaoCadastrarProduto.setText("Cadastrar Produto");
        botaoCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(botaoSairUsuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelUsuarioLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoTelaGerarMovimentacao, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(botaoTelaGerarRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoTelaVisualizarEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCargoAreaUsuarioLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoCadastrarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCargoAreaUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(botaoTelaGerarMovimentacao)
                .addGap(18, 18, 18)
                .addComponent(botaoTelaGerarRelatorio)
                .addGap(18, 18, 18)
                .addComponent(botaoTelaVisualizarEstoque)
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrarProduto)
                .addGap(61, 61, 61)
                .addComponent(botaoSairUsuario)
                .addGap(39, 39, 39))
        );

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel3.setText("Valor (R$)");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel4.setText("Descrição");

        areasMovimentacao.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        areasMovimentacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Esportes", "Eventos", "Financeiro", "Social", "Produtos" }));
        areasMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areasMovimentacaoActionPerformed(evt);
            }
        });

        valorMovimentacao.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        descricaoMovimentacao.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        grupoVendaCompra.add(radioCompra);
        radioCompra.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        radioCompra.setText("Compra");

        grupoVendaCompra.add(radioVenda);
        radioVenda.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        radioVenda.setText("Venda");
        radioVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVendaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel5.setText("Movimentação de Caixa");

        botaoGerarMovimentacao.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        botaoGerarMovimentacao.setText("Gerar Movimentação");
        botaoGerarMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarMovimentacaoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel6.setText("Área");

        movimentacaoMensagem.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel18.setText("Venda de Produtos do Estoque");

        jLabel20.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel20.setText("Produto");

        produtosEstoque.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        produtosEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtosEstoqueActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel21.setText("Preço de Compra (R$)");

        labelPrecoCompraProduto.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel22.setText("Preço de Venda (R$)");

        labelPrecoVendaProduto.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        botaoRegistrarVenda.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        botaoRegistrarVenda.setText("Registrar Venda");
        botaoRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarVendaActionPerformed(evt);
            }
        });

        statusVenda.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel23.setText("Quantidade disponível");

        labelQuantidadeDisponivelProduto.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel24.setText("Quantidade");

        quantidadeProdutoVenda.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        javax.swing.GroupLayout movimentacaoLayout = new javax.swing.GroupLayout(movimentacao);
        movimentacao.setLayout(movimentacaoLayout);
        movimentacaoLayout.setHorizontalGroup(
            movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movimentacaoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel5)
                    .addGroup(movimentacaoLayout.createSequentialGroup()
                        .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(movimentacaoLayout.createSequentialGroup()
                                .addComponent(valorMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(radioVenda)
                                .addGap(18, 18, 18)
                                .addComponent(radioCompra))
                            .addComponent(descricaoMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(movimentacaoLayout.createSequentialGroup()
                                .addComponent(areasMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(botaoGerarMovimentacao))))
                    .addComponent(movimentacaoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(movimentacaoLayout.createSequentialGroup()
                        .addComponent(botaoRegistrarVenda)
                        .addGap(45, 45, 45)
                        .addComponent(statusVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(movimentacaoLayout.createSequentialGroup()
                        .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(movimentacaoLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(quantidadeProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(labelQuantidadeDisponivelProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(movimentacaoLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(produtosEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(movimentacaoLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(labelPrecoCompraProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(movimentacaoLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(labelPrecoVendaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        movimentacaoLayout.setVerticalGroup(
            movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movimentacaoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioVenda)
                    .addComponent(radioCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricaoMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(areasMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(movimentacaoLayout.createSequentialGroup()
                        .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoGerarMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(movimentacaoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel18)
                        .addGap(27, 27, 27)
                        .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(produtosEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelPrecoVendaProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(movimentacaoLayout.createSequentialGroup()
                        .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelQuantidadeDisponivelProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantidadeProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoRegistrarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelPrecoCompraProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        telasOperacoes.addTab("Menu Movimentação", movimentacao);

        gerarRelatorio.setAutoscrolls(true);

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel7.setText("Saldo Início Gestão (R$):");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel8.setText("Saldo Atual (R$):");

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel9.setText("Balanço (R$):");

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel10.setText("Quantidade Total de Membros:");

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel11.setText("Saldo da Área (R$):");

        areasExtrato.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        areasExtrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Esportes", "Eventos", "Financeiro", "Social", "Produtos" }));
        areasExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areasExtratoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel12.setText("Área em análise:");

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel13.setText("Quantidade de Membros da Área:");

        labelSaldoInicio.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        labelSaldoAtual.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        labelBalanco.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        labelTotalMembros.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel14.setText("Extrato e Relatório de Movimentações");

        labelMembrosArea.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        labelSaldoArea.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        botaoGerarRelatorio.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        botaoGerarRelatorio.setText("Gerar Relatório do Histórico de Movimentações");
        botaoGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarRelatorioActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel16.setText("Registrar retirada de encomenda");

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel17.setText("Telefone do cliente:");

        telefoneClienteRetirada.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        botaoRegistrarRetirada.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        botaoRegistrarRetirada.setText("Registrar Retirada");
        botaoRegistrarRetirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarRetiradaActionPerformed(evt);
            }
        });

        statusRetirada.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel15.setText("Nome do Produto");

        nomeProdutoRetirada.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        javax.swing.GroupLayout gerarRelatorioLayout = new javax.swing.GroupLayout(gerarRelatorio);
        gerarRelatorio.setLayout(gerarRelatorioLayout);
        gerarRelatorioLayout.setHorizontalGroup(
            gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gerarRelatorioLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(gerarRelatorioLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefoneClienteRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(nomeProdutoRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoGerarRelatorio)
                    .addGroup(gerarRelatorioLayout.createSequentialGroup()
                        .addGroup(gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gerarRelatorioLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSaldoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gerarRelatorioLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelBalanco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gerarRelatorioLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTotalMembros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gerarRelatorioLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSaldoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(92, 92, 92)
                        .addGroup(gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gerarRelatorioLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(areasExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gerarRelatorioLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSaldoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gerarRelatorioLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelMembrosArea, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel14)
                    .addGroup(gerarRelatorioLayout.createSequentialGroup()
                        .addComponent(botaoRegistrarRetirada)
                        .addGap(18, 18, 18)
                        .addComponent(statusRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        gerarRelatorioLayout.setVerticalGroup(
            gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gerarRelatorioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelMembrosArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelSaldoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gerarRelatorioLayout.createSequentialGroup()
                        .addGroup(gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSaldoAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelSaldoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areasExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))
                    .addGroup(gerarRelatorioLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBalanco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotalMembros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(botaoGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneClienteRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeProdutoRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(gerarRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRegistrarRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
        );

        telasOperacoes.addTab("Menu Relatório", gerarRelatorio);

        scrollVisualizarEstoque.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        tabelaEstoque.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        tabelaEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "ID", "Preço Compra (R$)", "Preço Venda (R$)", "Tamanho", "Qtdd. Disponível"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollVisualizarEstoque.setViewportView(tabelaEstoque);

        jLabel19.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel19.setText("Estoque de Produtos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel19)
                .addContainerGap(555, Short.MAX_VALUE))
            .addComponent(scrollVisualizarEstoque)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(scrollVisualizarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        telasOperacoes.addTab("Menu Estoque", jPanel5);

        jLabel25.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel25.setText("Cadastrar Novo Produto e suas Encomendas");

        jLabel26.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel26.setText("Nome");

        jLabel27.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel27.setText("Preço de Compra (R$)");

        jLabel28.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel28.setText("Preço de Venda (R$)");

        jLabel29.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel29.setText("Ano de Produção");

        anoProducaoProduto.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        precoVendaProduto.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        precoCompraProduto.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        nomeProduto.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        botaoCadastrarNovoProduto.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        botaoCadastrarNovoProduto.setText("Cadastrar Produto");
        botaoCadastrarNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarNovoProdutoActionPerformed(evt);
            }
        });

        escolheArquivoEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolheArquivoEncomendaActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel30.setText("Arquivo de Encomendas .csv do Produto");

        statusCadastrarProduto.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(precoCompraProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botaoCadastrarNovoProduto)
                        .addGap(18, 18, 18)
                        .addComponent(statusCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(escolheArquivoEncomenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel28)
                            .addGap(18, 18, 18)
                            .addComponent(precoVendaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel29)
                            .addGap(18, 18, 18)
                            .addComponent(anoProducaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precoVendaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anoProducaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(precoCompraProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escolheArquivoEncomenda, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrarNovoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        telasOperacoes.addTab("Menu Produto", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telasOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telasOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoTelaGerarMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTelaGerarMovimentacaoActionPerformed
        preencheComboBoxProdutoEstoque();
        telasOperacoes.setSelectedIndex(0);
    }//GEN-LAST:event_botaoTelaGerarMovimentacaoActionPerformed

    private void botaoTelaGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTelaGerarRelatorioActionPerformed
        // Atualiza os valores das labels referentes ao parâmetros da instância atleticaRegistrada
        labelSaldoInicio.setText(String.format("%.2f", atleticaRegistrada.getCaixa().getSaldoInicioGestao()));
        labelSaldoAtual.setText(String.format("%.2f", atleticaRegistrada.getCaixa().getSaldoAtual()));
        labelBalanco.setText(String.format("%.2f", atleticaRegistrada.getCaixa().getBalanco()));
        labelTotalMembros.setText(String.format("%d", atleticaRegistrada.getIntegrantes().size()));
        // Muda para a telaGerarRelatorio
        telasOperacoes.setSelectedIndex(1);
    }//GEN-LAST:event_botaoTelaGerarRelatorioActionPerformed
    
    private void botaoSairUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairUsuarioActionPerformed
        close();
        Login login = new Login(atleticaRegistrada);
        login.setVisible(true);
    }//GEN-LAST:event_botaoSairUsuarioActionPerformed

    private void botaoTelaVisualizarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTelaVisualizarEstoqueActionPerformed
        // TODO Atualizar a tabela do visualizar estoque (VÍTOR)
        adicionaLinhasTabelaEstoque();
        telasOperacoes.setSelectedIndex(2);
    }//GEN-LAST:event_botaoTelaVisualizarEstoqueActionPerformed

    private void botaoCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarProdutoActionPerformed
        telasOperacoes.setSelectedIndex(3);
    }//GEN-LAST:event_botaoCadastrarProdutoActionPerformed

    private void escolheArquivoEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolheArquivoEncomendaActionPerformed
        pathEncomendasProduto = escolheArquivoEncomenda.getSelectedFile().getAbsolutePath();
    }//GEN-LAST:event_escolheArquivoEncomendaActionPerformed

    private void botaoCadastrarNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarNovoProdutoActionPerformed
        // Verificamos se todos as campos da interface gráfica para cadastrar novo produto estão preenchidos
        if (!nomeProduto.getText().isEmpty() && !precoCompraProduto.getText().isEmpty()
            && !precoVendaProduto.getText().isEmpty() && !anoProducaoProduto.getText().isEmpty()
            && !pathEncomendasProduto.isEmpty()) {

            Double numericoPrecoCompra, numericoPrecoVenda;

            try { // Trata a exceção para a entrada de precoCompraProduto e precoVendaProduto diferente de Double
                numericoPrecoCompra = Double.valueOf(precoCompraProduto.getText());
                numericoPrecoVenda = Double.valueOf(precoVendaProduto.getText());
            } catch(NumberFormatException ex) {
                statusCadastrarProduto.setForeground(Color.red);
                statusCadastrarProduto.setText("ERRO: Preço de compra ou venda preenchidos com formato inválido!");
                return;
            }

            String textoNomeProduto = nomeProduto.getText();
            String textoAnoProducaoProduto = anoProducaoProduto.getText();

            Area produtos = atleticaRegistrada.getArea("Produtos");
            Produtos produtosAtletica = (Produtos) produtos; // Downcast

            // Cria um novo produto para os parâmetros validados
            if (produtosAtletica.novoProduto(this, textoNomeProduto, numericoPrecoCompra, numericoPrecoVenda, textoAnoProducaoProduto, pathEncomendasProduto)) {
                statusCadastrarProduto.setForeground(Color.green);
                statusCadastrarProduto.setText("Produto cadastrado e encomendas registradas com sucesso!");
            } else {
                statusCadastrarProduto.setForeground(Color.red);
                statusCadastrarProduto.setText("ERRO: Produto já registrado no sistema!");
            }

        } else {
            statusCadastrarProduto.setForeground(Color.red);
            statusCadastrarProduto.setText("ERRO: Há campos não preenchidos!");
        }
    }//GEN-LAST:event_botaoCadastrarNovoProdutoActionPerformed

    private void botaoGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarRelatorioActionPerformed
        // Chama o método de gerarRelatorio() das movimentações do caixa associado a atlética
        atleticaRegistrada.getCaixa().gerarRelatorio();
    }//GEN-LAST:event_botaoGerarRelatorioActionPerformed

    private void areasExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areasExtratoActionPerformed
        int selection = areasExtrato.getSelectedIndex();
        Area areaSelecionada;

        switch (selection) {
            case 0: // Esportes
                areaSelecionada = atleticaRegistrada.getArea("Esportes");
                break;
            case 1: // Eventos
                areaSelecionada = atleticaRegistrada.getArea("Eventos");
                break;
            case 2: // Financeiro
                areaSelecionada = atleticaRegistrada.getArea("Financeiro");
                break;
            case 3: // Social
                areaSelecionada = atleticaRegistrada.getArea("Social");
                break;
            case 4: // Produtos
                areaSelecionada = atleticaRegistrada.getArea("Produtos");
                break;
            default: // ERRO: Area não encontrada na instância de atlética
                areaSelecionada = null;
                break;
        }

        if (areaSelecionada != null) {
            labelMembrosArea.setText(String.format("%d", areaSelecionada.quantidadeInteressados()));
            labelSaldoArea.setText(String.format("%.2f", areaSelecionada.getSaldoFinanceiro()));
        }
    }//GEN-LAST:event_areasExtratoActionPerformed

    private void produtosEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtosEstoqueActionPerformed
        String produtoEscolhido;
        
        try { // Trata a exceção para a escolha de produtoEscolhido pela comboBox produtosEstoque
            produtoEscolhido = produtosEstoque.getSelectedItem().toString();
        } catch(NumberFormatException ex) {
            System.out.println("Produto não encontrado!");
            return;
        }
        
        String[] informacoes = produtoEscolhido.split(" - ");
        String nomeProduto = informacoes[0];
        String tamanhoProduto = informacoes[1];
        
        Area area = atleticaRegistrada.getArea("Produtos");
        Produtos areaProdutosAtletica = (Produtos) area; // Downcast
        
        Produto escolhido = areaProdutosAtletica.buscaProdutoPeloNome(nomeProduto);
        labelPrecoVendaProduto.setText(String.format("%.2f", escolhido.getPrecoVenda()));
        labelPrecoCompraProduto.setText(String.format("%.2f", escolhido.getPrecoCompra()));
        
        Item itemEscolhido = escolhido.buscarItem(tamanhoProduto);
        labelQuantidadeDisponivelProduto.setText(String.format("%d", itemEscolhido.getQuantidadeDisponivel()));
    }//GEN-LAST:event_produtosEstoqueActionPerformed

    private void botaoGerarMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarMovimentacaoActionPerformed
        // Verificamos se todos as campos da interface gráfica para gerar movimentação estão preenchidos
        if (!valorMovimentacao.getText().isEmpty() && !descricaoMovimentacao.getText().isEmpty()
            && (radioVenda.isSelected() || radioCompra.isSelected())) {

            Double numericoValorMovimentacao;

            try { // Trata a exceção para a entrada de valorMovimentação diferente de Double
                numericoValorMovimentacao = Double.valueOf(valorMovimentacao.getText());
            } catch(NumberFormatException ex) {
                movimentacaoMensagem.setForeground(Color.red);
                movimentacaoMensagem.setText("ERRO: Campo Valor (R$) preenchido com formato inválido!");
                return;
            }

            if (radioCompra.isSelected()) { // Compra, ou seja, valorMovimentacao tem sinal negativo
                // Verifica se a movimentação é possível para o valor disponível na instância atleticaRegistrada
                if (numericoValorMovimentacao <= atleticaRegistrada.getCaixa().getSaldoAtual()) {
                    if (atleticaRegistrada.validarMovimentacao(usuarioLogado,numericoValorMovimentacao)) {
                        numericoValorMovimentacao = -numericoValorMovimentacao;
                    } else {
                        movimentacaoMensagem.setForeground(Color.red);
                        movimentacaoMensagem.setText("ERRO: Valor da movimentação não compatível com o cargo!");
                        return;
                    }
                } else {
                    movimentacaoMensagem.setForeground(Color.red);
                    movimentacaoMensagem.setText("ERRO: Valor da movimentação excede o saldo da Atlética!");
                    return;
                }
            }   

            String textoDescricaoMovimentacao = descricaoMovimentacao.getText();
            String textoArea = areasMovimentacao.getSelectedItem().toString();
            Area areaSelecionada = atleticaRegistrada.getArea(textoArea);

            // Gera uma movimentação para os parâmetros validados
            if (atleticaRegistrada.getCaixa().gerarMovimentacao(numericoValorMovimentacao, textoDescricaoMovimentacao,
                areaSelecionada, usuarioLogado)) {
                movimentacaoMensagem.setForeground(Color.green);
                movimentacaoMensagem.setText("Movimentação registrada com sucesso!");
            } else {
                movimentacaoMensagem.setForeground(Color.red);
                movimentacaoMensagem.setText("ERRO: Movimentação já registrada no sistema!");
            }

        } else {
            movimentacaoMensagem.setForeground(Color.red);
            movimentacaoMensagem.setText("ERRO: Há campos não preenchidos!");
        }
    }//GEN-LAST:event_botaoGerarMovimentacaoActionPerformed

    private void radioVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioVendaActionPerformed

    private void areasMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areasMovimentacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areasMovimentacaoActionPerformed

    private void botaoRegistrarRetiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarRetiradaActionPerformed
        if (!nomeProdutoRetirada.getText().isEmpty() && !telefoneClienteRetirada.getText().isEmpty()) {
            
            Area area = atleticaRegistrada.getArea("Produtos");
            Produtos areaProdutosAtletica = (Produtos) area; // Downcast
            
            if (areaProdutosAtletica.encomendaRetirada(nomeProdutoRetirada.getText(), telefoneClienteRetirada.getText())) {
                statusRetirada.setForeground(Color.green);
                statusRetirada.setText("Retirada(s) registrada(s) com sucesso!");
            } else {
                statusRetirada.setForeground(Color.red);
                statusRetirada.setText("ERRO: Retirada de produto inválida!");
            }
            
        } else {
            statusRetirada.setForeground(Color.red);
            statusRetirada.setText("ERRO: Há campos não preenchidos!");
        }
    }//GEN-LAST:event_botaoRegistrarRetiradaActionPerformed

    private void botaoRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarVendaActionPerformed
        if (!quantidadeProdutoVenda.getText().isEmpty()) {
            
            int numericoQuantidadeProdutoVenda;

            try { // Trata a exceção para a entrada de quantidadeProdutoVenda diferente de int
                numericoQuantidadeProdutoVenda = Integer.parseInt(quantidadeProdutoVenda.getText());
            } catch(NumberFormatException ex) {
                statusVenda.setForeground(Color.red);
                statusVenda.setText("ERRO: Campo Quantidade preenchido com formato inválido!");
                return;
            }
            
            int quantidadeDisponivel;
            
            try { // Trata a exceção para a tentatica de ler o valor de quantidade disponivel apresentado na labelQuantidadeDisponivelProduto 
                quantidadeDisponivel = Integer.parseInt(labelQuantidadeDisponivelProduto.getText());
            } catch(NumberFormatException ex) {
                statusVenda.setForeground(Color.red);
                statusVenda.setText("ERRO: Produto não selecionado!");
                return;
            }
            
            if (numericoQuantidadeProdutoVenda <= quantidadeDisponivel && numericoQuantidadeProdutoVenda > 0) {
                String produtoEscolhido = produtosEstoque.getSelectedItem().toString();
                String[] informacoes = produtoEscolhido.split(" - ");
                String nomeProduto = informacoes[0];
                String tamanhoProduto = informacoes[1];
                Area area = atleticaRegistrada.getArea("Produtos");
                Produtos areaProdutosAtletica = (Produtos) area; // Downcast
                Produto escolhido = areaProdutosAtletica.buscaProdutoPeloNome(nomeProduto);
                Item itemEscolhido = escolhido.buscarItem(tamanhoProduto);
                escolhido.venderProduto(itemEscolhido, usuarioLogado, numericoQuantidadeProdutoVenda);
                labelQuantidadeDisponivelProduto.setText(String.format("%d", itemEscolhido.getQuantidadeDisponivel()));
                statusVenda.setForeground(Color.green);
                statusVenda.setText("Venda registrada com sucesso!");
            } else {
                statusVenda.setForeground(Color.red);
                statusVenda.setText("ERRO: Quantidade de produtos solicitada inválida!");
            }
            
        } else {
            statusVenda.setForeground(Color.red);
            statusVenda.setText("ERRO: Há campos não preenchidos!");
        }
    }//GEN-LAST:event_botaoRegistrarVendaActionPerformed
    
    private void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    private void adicionaLinhasTabelaEstoque() {
        DefaultTableModel model = (DefaultTableModel) tabelaEstoque.getModel();
        model.setRowCount(0); // Limpa a tabela antes de apresentar os dados
        Object dadosLinha[] = new Object[7];
        
        Area area = atleticaRegistrada.getArea("Produtos");
        Produtos areaProdutosAtletica = (Produtos) area; // Downcast
        
        for (Produto p : areaProdutosAtletica.getListaProdutos()) {
            dadosLinha[0] = p.getNome();
            dadosLinha[1] = p.getID();
            dadosLinha[2] = p.getPrecoCompra();
            dadosLinha[3] = p.getPrecoVenda();
            for (Item i : p.getEstoque()) {
                dadosLinha[4] = i.getTamanho();
                dadosLinha[5] = i.getQuantidadeDisponivel();
                model.addRow(dadosLinha);
            }
        }
    }
    
    private void preencheComboBoxProdutoEstoque() {
        
        Area area = atleticaRegistrada.getArea("Produtos");
        Produtos areaProdutosAtletica = (Produtos) area; // Downcast
        String itemComboBox;
        
        for (Produto p : areaProdutosAtletica.getListaProdutos()) {
            for (Item i : p.getEstoque()) {
                itemComboBox = p.getNome();
                itemComboBox += " - " + i.getTamanho();
                if(((DefaultComboBoxModel)produtosEstoque.getModel()).getIndexOf(itemComboBox) == -1) {
                    produtosEstoque.addItem(itemComboBox);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anoProducaoProduto;
    private javax.swing.JComboBox<String> areasExtrato;
    private javax.swing.JComboBox<String> areasMovimentacao;
    private javax.swing.JButton botaoCadastrarNovoProduto;
    private javax.swing.JButton botaoCadastrarProduto;
    private javax.swing.JButton botaoGerarMovimentacao;
    private javax.swing.JButton botaoGerarRelatorio;
    private javax.swing.JButton botaoRegistrarRetirada;
    private javax.swing.JButton botaoRegistrarVenda;
    private javax.swing.JButton botaoSairUsuario;
    private javax.swing.JButton botaoTelaGerarMovimentacao;
    private javax.swing.JButton botaoTelaGerarRelatorio;
    private javax.swing.JButton botaoTelaVisualizarEstoque;
    private javax.swing.JTextField descricaoMovimentacao;
    private javax.swing.JFileChooser escolheArquivoEncomenda;
    private javax.swing.JPanel gerarRelatorio;
    private javax.swing.ButtonGroup grupoVendaCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelBalanco;
    private javax.swing.JLabel labelCargoAreaUsuarioLogado;
    private javax.swing.JLabel labelMembrosArea;
    private javax.swing.JLabel labelPrecoCompraProduto;
    private javax.swing.JLabel labelPrecoVendaProduto;
    private javax.swing.JLabel labelQuantidadeDisponivelProduto;
    private javax.swing.JLabel labelSaldoArea;
    private javax.swing.JLabel labelSaldoAtual;
    private javax.swing.JLabel labelSaldoInicio;
    private javax.swing.JLabel labelTotalMembros;
    private javax.swing.JLabel labelUsuarioLogado;
    private javax.swing.JPanel movimentacao;
    private javax.swing.JLabel movimentacaoMensagem;
    private javax.swing.JTextField nomeProduto;
    private javax.swing.JTextField nomeProdutoRetirada;
    private javax.swing.JTextField precoCompraProduto;
    private javax.swing.JTextField precoVendaProduto;
    private javax.swing.JComboBox<String> produtosEstoque;
    private javax.swing.JTextField quantidadeProdutoVenda;
    private javax.swing.JRadioButton radioCompra;
    private javax.swing.JRadioButton radioVenda;
    private javax.swing.JScrollPane scrollVisualizarEstoque;
    private javax.swing.JLabel statusCadastrarProduto;
    private javax.swing.JLabel statusRetirada;
    private javax.swing.JLabel statusVenda;
    private javax.swing.JTable tabelaEstoque;
    private javax.swing.JTabbedPane telasOperacoes;
    private javax.swing.JTextField telefoneClienteRetirada;
    private javax.swing.JTextField valorMovimentacao;
    // End of variables declaration//GEN-END:variables
}
