
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

public class MenuOperacoes extends javax.swing.JFrame {

    /**
     * Creates new form MenuOperacoes
     * @param raUsuario
     */
    public MenuOperacoes(String raUsuario) {
        initComponents();
        usuarioLogado.setText("Usuário logado: " + raUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoVendaCompra = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        botaoTelaMovimentacao = new javax.swing.JButton();
        botaoTelaRelatorio = new javax.swing.JButton();
        botaoTelaCadastrar = new javax.swing.JButton();
        botaoTelaRemover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoSairUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        usuarioLogado = new javax.swing.JLabel();
        telasOperacoes = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        movimentacao = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        areasMovimentacao = new javax.swing.JComboBox<>();
        valorMovimentacao = new javax.swing.JTextField();
        descricaoMovimentacao = new javax.swing.JTextField();
        radioCompra = new javax.swing.JRadioButton();
        radioVenda = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        botaoGerarMovimentacao = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        movimentacaoMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Operações - Sistema de Gerenciamento AAAECA");
        setName("telaMenu"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        botaoTelaMovimentacao.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        botaoTelaMovimentacao.setText("Gerar Movimentação");
        botaoTelaMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTelaMovimentacaoActionPerformed(evt);
            }
        });

        botaoTelaRelatorio.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        botaoTelaRelatorio.setText("Gerar Relatório");
        botaoTelaRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTelaRelatorioActionPerformed(evt);
            }
        });

        botaoTelaCadastrar.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        botaoTelaCadastrar.setText("Cadastrar Membro");
        botaoTelaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTelaCadastrarActionPerformed(evt);
            }
        });

        botaoTelaRemover.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        botaoTelaRemover.setText("Remover Membro");
        botaoTelaRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTelaRemoverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 3, 20)); // NOI18N
        jLabel1.setText("Operações");

        botaoSairUsuario.setFont(new java.awt.Font("FreeSans", 1, 16)); // NOI18N
        botaoSairUsuario.setForeground(new java.awt.Color(255, 0, 0));
        botaoSairUsuario.setText("SAIR");
        botaoSairUsuario.setName("botaoSairUsuario"); // NOI18N
        botaoSairUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoinblack.png"))); // NOI18N

        usuarioLogado.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        usuarioLogado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioLogado)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botaoTelaMovimentacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoTelaRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoTelaCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoTelaRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(botaoSairUsuario)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usuarioLogado)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(botaoTelaMovimentacao)
                .addGap(18, 18, 18)
                .addComponent(botaoTelaRelatorio)
                .addGap(18, 18, 18)
                .addComponent(botaoTelaCadastrar)
                .addGap(18, 18, 18)
                .addComponent(botaoTelaRemover)
                .addGap(84, 84, 84)
                .addComponent(botaoSairUsuario)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        telasOperacoes.addTab("gerarRelatorio", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        telasOperacoes.addTab("cadastrarMembro", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        telasOperacoes.addTab("removerMembro", jPanel5);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Valor R$");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel4.setText("Descrição");

        areasMovimentacao.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        areasMovimentacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Esportes", "Eventos", "Financeiro", "Social", "Produtos" }));

        grupoVendaCompra.add(radioCompra);
        radioCompra.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        radioCompra.setText("Compra");

        grupoVendaCompra.add(radioVenda);
        radioVenda.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        radioVenda.setText("Venda");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel5.setText("Movimentação de Caixa - AAAECA");

        botaoGerarMovimentacao.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        botaoGerarMovimentacao.setText("Gerar Movimentação");
        botaoGerarMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarMovimentacaoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Área");

        movimentacaoMensagem.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        movimentacaoMensagem.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout movimentacaoLayout = new javax.swing.GroupLayout(movimentacao);
        movimentacao.setLayout(movimentacaoLayout);
        movimentacaoLayout.setHorizontalGroup(
            movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movimentacaoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(movimentacaoLayout.createSequentialGroup()
                        .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(movimentacaoLayout.createSequentialGroup()
                                .addComponent(valorMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(radioVenda)
                                .addGap(18, 18, 18)
                                .addComponent(radioCompra))
                            .addComponent(descricaoMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(movimentacaoLayout.createSequentialGroup()
                                .addComponent(areasMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(botaoGerarMovimentacao))))
                    .addComponent(movimentacaoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        movimentacaoLayout.setVerticalGroup(
            movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movimentacaoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel5)
                .addGap(61, 61, 61)
                .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioVenda)
                    .addComponent(radioCompra))
                .addGap(18, 18, 18)
                .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descricaoMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(movimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoGerarMovimentacao, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(areasMovimentacao, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27)
                .addComponent(movimentacaoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        telasOperacoes.addTab("movimentacao", movimentacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(telasOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telasOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoTelaMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTelaMovimentacaoActionPerformed
        telasOperacoes.setSelectedIndex(3);
    }//GEN-LAST:event_botaoTelaMovimentacaoActionPerformed

    private void botaoTelaRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTelaRelatorioActionPerformed
        telasOperacoes.setSelectedIndex(0);
    }//GEN-LAST:event_botaoTelaRelatorioActionPerformed
    
    private void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    private void botaoSairUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairUsuarioActionPerformed
        close();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_botaoSairUsuarioActionPerformed

    private void botaoGerarMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarMovimentacaoActionPerformed
        // TODO: Temos que fazer nessa parte também a verificação de se o cargo do usuário permite a movimentação, jogar exceção para usuário na tela com mensagem de erro
        if (!valorMovimentacao.getText().isEmpty() && !descricaoMovimentacao.getText().isEmpty()
                && (radioVenda.isSelected() || radioCompra.isSelected())) {
            // TODO: Fazer validacao se valorMovimentacao é um double, jogar exceção para usuário na tela com mensagem de erro em movimentacaoInvalida
            
            
            
            movimentacaoMensagem.setForeground(Color.green);
            movimentacaoMensagem.setText("Movimentação registrada com sucesso!");
        } else {
            movimentacaoMensagem.setForeground(Color.red);
            movimentacaoMensagem.setText("ERRO: Há campos não preenchidos!");
        }
    }//GEN-LAST:event_botaoGerarMovimentacaoActionPerformed

    private void botaoTelaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTelaCadastrarActionPerformed
        telasOperacoes.setSelectedIndex(1);
    }//GEN-LAST:event_botaoTelaCadastrarActionPerformed

    private void botaoTelaRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTelaRemoverActionPerformed
        telasOperacoes.setSelectedIndex(2);
    }//GEN-LAST:event_botaoTelaRemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> areasMovimentacao;
    private javax.swing.JButton botaoGerarMovimentacao;
    private javax.swing.JButton botaoSairUsuario;
    private javax.swing.JButton botaoTelaCadastrar;
    private javax.swing.JButton botaoTelaMovimentacao;
    private javax.swing.JButton botaoTelaRelatorio;
    private javax.swing.JButton botaoTelaRemover;
    private javax.swing.JTextField descricaoMovimentacao;
    private javax.swing.ButtonGroup grupoVendaCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel movimentacao;
    private javax.swing.JLabel movimentacaoMensagem;
    private javax.swing.JRadioButton radioCompra;
    private javax.swing.JRadioButton radioVenda;
    private javax.swing.JTabbedPane telasOperacoes;
    private javax.swing.JLabel usuarioLogado;
    private javax.swing.JTextField valorMovimentacao;
    // End of variables declaration//GEN-END:variables
}
